### ISSUE TITLE
Allow to switch between desktop & mobile versions

### ISSUE THREAD

**Issue by KazeJiyu** [robjullian/shuttle#10]
Due to Shuttle's size websites render their mobile version by default.

However, it could be handy to be able to change this behavior on the fly. For exemple, [Messenger](messenger.com) is unusable in its mobile version because the site asks for the download of the application.

We could, for example, provide a context menu on icons that allows the user to choose between the mobile and the desktop version.

**Comment by robjullian** [comment]
added
